package com.propertymanager.domain.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId

data class Notification(
    @DocumentId val id: String = "", // Auto-generated by Firestore
    val userId: String = "", // Reference to User.id
    val message: String = "",
    val type: String = "maintenanceUpdate", //type, "maintenanceUpdate" | "taskAssigned" | etc
    val read: Boolean = false, // True if notification is read
    val createdAt: Timestamp? = Timestamp.now() // Firestore timestamp
) {
    // Secondary constructor for Firestore (no-argument constructor)
    constructor() : this(
        id = "",
        userId = "",
        message = "",
        type = "maintenanceUpdate",
        read = false,
        createdAt = Timestamp.now()
    )
}
